#!/usr/bin/env bash
# This bash script transfers a file from a client to a server.

# Declare the placeholders for the expected variables and assign parameters.
file_path=$1
server_ip=$2
username=$3
ssh_key=$4

# Check that the variables provided aren't less than 3
if [ $# -lt 3 ]; then
	echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
# Use scp to transfer the file
scp -o StrictHostKeyChecking=no -i "$ssh_key" "$file_path" "$username@$server_ip":~
fi
