#!/usr/bin/env bash
# Commands to install Nginx
sudo apt-get -y update
sudo apt-get install -y nginx

# Configuring the directory structure
mkdir /etc/nginx/html

# Creating a Sample Page
echo "Hello World!" > /etc/nginx/html/index.html

# Configuring the server block file
echo "server {
	listen 80 default_server;
	listen [::]:80 default_server;
	
	root /etc/nginx/html;
	index index.html index.htm index.nginx-debian.html

	server_name _;
}" > /etc/nginx/sites-available/default

# Restarting Nginx
sudo service nginx restart
