#!/usr/bin/env bash
# This bash script installs Nginx on a server
	# configures it to listen on port 80
	# when queried with a get request,
	# it should return "Hello World!"

sudo apt-get update
sudo apt-get install nginx -y

# Configure it to listen on port 80
ufw allow 'Nginx HTTP'

# Create a sample page that will return the string
echo "Hello World!" > /var/www/html/index.html

# Start the nginx service
service nginx start

