#!/usr/bin/env bash

# This script installs nginx on the server.
sudo apt-get install nginx -y

# Configure nginx to listen on port 80
# Display all application profiles
sudo ufw allow 'Nginx HTTP'

# restart nginx without using the systemctl command-line utility
sudo service nginx restart

