#!/usr/bin/env bash
# This script configures the Nginx server to redirect to another page permanently.

# The replacement string to use
replacement_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com permanent;"

# This is the command that configures the server to redirect to another page
sudo sed -i "s/server_name _;/$replacement_string/" /etc/nginx/sites-enabled/default

# This command tests Nginx configuration before reloading it.
sudo service nginx restart
