#!/usr/bin/env bash
# Install Nginx and configure it to have a custom 404 page that returns a string on error

sudo apt-get update
sudo apt-get install nginx -y

# Writing the error message into the 404.html error file
echo "Ceci n'est pas une page" > /etc/nginx/html/404.html

# String to use when replacing the file content
replacement_String="server_name _;\n\terror_page 404 \/404.html;\nlocation = 404.html {\n\t\troot \/etc\/nginx\/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# Restart nginx service
sudo service nginx restart
