#!/usr/bin/bash
# This script installs and configures HAproxy on the server
# It also implements load balancing using roundrobin algorithm


sudo apt-get update
sudo apt-get install haproxy -y

# This block configures the frontend and backend of the server
echo "
frontend lb-01
	bind *:80
	default_backend be-01
	
backend be-01
	balance roundrobin
	server 167989-web-01 54.157.176.30:80 check
	server 167989-web-02 54.160.90.163:80 check
" >> /etc/haproxy/haproxy.cfg

# This line of code enables HAproxy on the server
sudo sed -i 's/ENABLED=0/ENABLED=1/g' /etc/default/haproxy

# Restart the service
sudo service haproxy restart
