#!/usr/bin/env bash
# This script uses the concept of fizzbuzz on multiples of 3 and 5 while
# printing numbers from 0 to 100

for num in {1..100}
do
	if (( num % 3 == 0 && num % 5 == 0 ))
	then
		echo "FizzBuzz"
	elif (( num % 3 == 0 ))
	then
		echo "Fizz"
	elif (( num % 5 == 0 ))
	then
		echo "Buzz"
	else
		echo "$num"
	fi
done
