#!/usr/bin/env bash
# Bash script that displays different stetements depending on the iteration
# sequence using while and case

i=1

while [ $i -le 20 ]
do
	echo "$i"
	case $i in
	"4") echo "bad luck from China";;
	"9") echo "bad luck from Japan";;
	"17") echo "bad luck from Italy";;
	esac
	((i++))
done
