#!/usr/bin/env bash
# Run nginx as nginx user

# change the mode for the config file of nginx
chmod 644 /etc/nginx/nginx.conf
# replace the user of in nginx.conf to nginx user
sed -i 's/user www-data/user nginx/' /etc/nginx/nginx.conf
# change port number from port 80 to 8080
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
# kill apache2 service because of port conflict with nginx
pkill apache2
# start nginx service
sudo -u nginx service nginx start
